version: "3.7"
services:
  client:
    build:
      context: ../cake_shop_frontend_react_rest
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ../cake_shop_frontend_react_rest:/app
      - /app/node_modules
    depends_on:
      - api
  api:
    build:
      context: ../cake_shop_backend_flask_rest
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 main:app
    ports:
      - 5000:5000
    environment:
      POSTGRES_PASSWORD: my_password
      POSTGRES_USER: cake_shop_admin
      POSTGRES_DB: cake_shop
      DB_SERVER_NAME: db
      JWT_SECRET_KEY: my_secret_key
      SETUP_KEY: my_setup_key
      FLASK_ENV: production
    volumes:
      - appdata:/var/www/
    networks:
      - frontend
      - backend
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: my_password
      POSTGRES_USER: main
      POSTGRES_DB: data
    volumes:
      - ${HOME}/volumes/cake_shop/:/var/lib/postgresql/data
    networks:
      - backend
  db_admin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.local
      PGADMIN_DEFAULT_PASSWORD: my_password
    networks:
      - backend
    depends_on:
      - db
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  appdata:
    driver: local
